dist: trusty

jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t shiro.py .
    - docker images
    - docker tag latest $DOCKER_USERNAME/shiro.py
    - docker push $DOCKER_USERNAME/shiro.py
  - stage: test
    script: docker run --rm $DOCKER_USERNAME/shiro.py cat hello.txt
  - script: docker run --rm $DOCKER_USERNAME/shiro.py cat hello.txt