jobs:
  include:
    - stage: test coverage
      env:
        - POSTGRES_HOST=localhost
        - POSTGRES_PORT=5432
        - POSTGRES_DATABASE=shiro
        - POSTGRES_USER=shiro
        - POSTGRES_PASSWORD=shiro
        - LAVALINK_HOST=localhost
        - LAVALINK_PORT=2333
        - LAVALINK_PASSWORD=youshallnotpass
        - LAVALINK_REGION=eu
        - secure: wGK5i30+b7NxoVPPS4Uid941wEE3cPFDwhbKSeQON8rbSDRMwFl1YEzfWddMOAeyYnpsat/O1v4s1+6xUuo/zqv0CcxkKoqJ596qP0o3l6hB9brCPEl/ZQEOjA+ylxpdX4Xd6nz8lXzej/9O6lhz7PdmgYCdxFSbjkuANX6/Z3HXmMfBq1JwGT401IoEaPtUIHrzHmuw7BcYqz2i7T/4q93vdH+m6mU70+5PkFYZfxSIQssby1QwmqOC+MwVjEwZ3KGEr7JF8Wr97aMO/MS2fvxSHKCH2v6awoglT1gYLsL31kLT827M+1OEfWksd27oUcyJchlWXSYEf7OOddQDe6X94Op6IFizFI96jOZAGj5641oIsJzJlfudMQEDAu+NLsb+btSKFdGAjZOOKLv94kL5tST3XNhznozSqcKEVS13u3IbP/W+pBeF3+ik7az7RlrhEyHj+ofV7zDvvf7s73ELLgMEZiYut0fglKqqqIdjQ+6/7cUdZzekB2vghNh5MqdykuyMwDGB2gahCC930lNdozfyHTIWbFtD3AOY8F1i+bLwRgJUO/AYxqkPlbGmVWKDIpyGs9QmrbFnd3azZBFAIpwJG/fz+R83qhvKhLfuGDY3IALDrjcdj///2aDj04eBrM+pk71Ts4H0hq8NwN/h/Mzms0bxS+zYutfA/3U=
      dist: xenial
      language: python
      python: "3.7"
      services: postgresql
      before_install:
        - pip install coverage
        - pip install codacy-coverage
        - docker pull fredboat/lavalink
        - docker run -d -p 2333:2333 fredboat/lavalink
      before_script:
        - psql -c "create database $POSTGRES_DATABASE;" -U postgres
        - psql -c "create user $POSTGRES_USER with password '$POSTGRES_PASSWORD';" -U postgres
      script:
        - coverage run shiro.py
      after_success:
        - coverage xml
        - python-codacy-coverage -r coverage.xml
    - stage: build docker image
      env:
        - DOCKER_USERNAME=mrspinne
        - secure: EpUfXKASylABRk5lFhaec5HFE6RikGgoXOf3TAUaNegS2G/cEEXLhfH3mDM1zGg2YyIG6Ut/6wKJ4v07XLGJQngNTSog5jZr7s27r4q+kb2y1sFMm3K50LcXpAFZw/aGh05WxMUlW3s5YvgCa0z09he3G2fps6AUxtzzS6HYbax97fcloqa6dA68J6/nEpCLE+yHvwzT7V75RCk6INOd66vOdotL2RE/s6sbWohV1mf0sZI2husr4WsfeN9i+BsUD+pmoswJw5pSKtLK3RgjHdHayfKzZvrZh8NSKeuvz+zxUwalXR9RLjfByyj9Y5y8vB9LATkyDMUcBQ6xUQh99sbYMohmSpgLl57ta9zydr6kA2vvsSIihw4aJE4rC505CFx7oRTq3BEaBqxJ4Uv/wUext5sNnlkt40a5vZuvRgygWJu9QT+iVZPf6nSHqV5GJociG22AG3UW8/GMqEACnap0AOzXJj3m6MB5Y9OL7kGK1WQf6w9xQoCKOQtphJgqj3LHJeSpCPOlfRaMPDxDp3GWpHR6bwI/d0Ca6qFIZjAZ263MoXV8m/S4v2T+1UE3BUM6hRG6EudMZ82FjFhLe7n7Mida2ds+iRQgzxoTM5UzB+d+Ji83mp+xjoAN2P4J3C/h1q/FZdwyf+AA1uTuklDlBn1gEOz7JB5VlVlfL7s=
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t shiro.py .
        - docker images
        - docker tag shiro.py $DOCKER_USERNAME/shiro.py:$TRAVIS_BRANCH
      after_success:
        - docker push $DOCKER_USERNAME/shiro.py:$TRAVIS_BRANCH