dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE shiropy;" -U postgres
  - psql -c "CREATE USER shiropy WITH PASSWORD 'shiropy';" -U postgres