dist: xenial
language: python
python:
  - "3.7"

env:
  - POSTGRES_HOST=localhost POSTGRES_PORT=5432 POSTGRES_DATABASE=shiro POSTGRES_USER=shiro POSTGRES_PASSWORD=shiro LAVALINK_HOST=localhost LAVALINK_PORT=2333 LAVALINK_PASSWORD=youshallnotpass

services:
  - docker

before_install:
  - docker pull postgres
  - docker pull fredboat/lavalink:master

install:
  - pip install -r requirements.txt

before_script:
  - docker run -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_USER=$POSTGRES_USER POSTGRES_DB=$POSTGRES_DATABASE -d -p $POSTGRES_PORT:$POSTGRES_PORT postgres
  - docker run -d -p 2333:2333 fredboat/lavalink:master

script:
  - python shiro.py