dist: xenial
language: python
python:
  - "3.7"

env:
  - POSTGRES_HOST=localhost POSTGRES_PORT=5432 POSTGRES_DATABASE=shiro POSTGRES_USER=shiro POSTGRES_PASSWORD=shiro

services:
  - docker
  - postgresql

before_install:
  - psql -c "CREATE DATABASE $POSTGRES_DATABASE;" -U postgres
  - psql -c "CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';" -U postgres
  - docker pull fredboat/lavalink:master
  - docker run -p 2333:2333 fredboat/lavalink:master

install:
  - pip install -r requirements.txt

script:
  - python shiro.py